In [5]:
from tmdbv3api import TMDb, Discover

tmdb = TMDb()
tmdb.api_key = 'fd5bdbb2e9284468c4f6a4f3dc74a1e4'

discover = Discover()
movies = []
for date in range(1950, 2023):
    for page in range(1,6):
        movies += discover.discover_movies({"primary_release_year":date, "page":page})

len(movies)

7300

In [ ]:
# import requests
# import json

# r = requests.get('https://api.themoviedb.org/3/discover/movie?api_key=fd5bdbb2e9284468c4f6a4f3dc74a1e4&language=en-US&include_video=false')
# len(r.json()["results"])

In [12]:
import csv
import pandas as pd

with open('movies.csv', 'w') as csvfile:
    writer = csv.DictWriter(csvfile, ["adult", "backdrop_path", "genre_ids", "id", "original_language", "original_title", "overview", "popularity", "poster_path", "release_date", "title", "video", "vote_average", "vote_count"])
    writer.writeheader()
    writer.writerows(movies)



df = pd.read_csv("movies.csv")

df.drop(columns=["backdrop_path", "poster_path", "adult", "video"])

,genre_ids,id,original_language,original_title,overview,popularity,release_date,title,vote_average,vote_count
0,"[10751, 14, 16, 10749]",11224,en,Cinderella,Cinderella has faith her dreams of a better li...,112.714,1950-02-22,Cinderella,7.0,5593
1,[18],599,en,Sunset Boulevard,A hack screenwriter writes a screenplay for a ...,17.698,1950-08-10,Sunset Boulevard,8.4,1912
2,[18],705,en,All About Eve,From the moment she glimpses her idol at the s...,15.744,1950-10-06,All About Eve,8.2,1181
3,"[18, 53, 80, 9648]",19119,en,Night and the City,Londoner Harry Fabian is a second-rate con man...,14.220,1950-06-15,Night and the City,7.6,178
4,"[80, 18, 9648]",548,ja,羅生門,Brimming with action while incisively examinin...,13.445,1950-08-26,Rashomon,8.2,1599
...,...,...,...,...,...,...,...,...,...,...
7295,"[35, 10749]",832277,it,4 metà,In this rom-com challenging the concept of sou...,91.984,2022-01-05,Four to Dinner,6.3,176
7296,[],901908,es,El juego de las llaves,"Laura has been with Antonio all her life and, ...",92.039,2022-04-13,El juego de las llaves,0.0,0
7297,[99],913862,en,Downfall: The Case Against Boeing,Investigators reveal how Boeing’s alleged prio...,85.281,2022-02-09,Downfall: The Case Against Boeing,7.4,74
7298,"[878, 35]",665828,fr,Bigbug,"Humans have ceded most tasks to AI in 2045, ev...",87.848,2022-02-11,Bigbug,5.4,202
7299,"[35, 10749]",892835,en,Book of Love,"Henry, an english writer who has written a new...",87.570,2022-01-06,Book of Love,5.4,25