In [1]:
import pandas as pd

In [14]:
df15 = pd.read_excel("data/ResmetBE15.xls", sheet_name=1)

In [15]:
df15

,Code bassin 2015,Nom bassin 2015,Famille métier,Libellé Famille métier,Métier,Libellé du métier,Code département,Nom Departement,Projets de recrutement totaux,Projets de recrutement difficiles,Projets de recrutement saisonniers,Code region,Nom Region
0,101,SAINTE-ROSE,Z,Autres métiers,A0Z40,"Agriculteurs salariés, ouvriers agricoles",971,GUADELOUPE,45.909687,0.000000,45.909687,1,GUADELOUPE
1,101,SAINTE-ROSE,Z,Autres métiers,A0Z43,Conducteurs d'engins agricoles ou forestiers,971,GUADELOUPE,8.636562,8.636562,8.636562,1,GUADELOUPE
2,101,SAINTE-ROSE,Z,Autres métiers,A1Z41,"Jardiniers salariés, paysagistes",971,GUADELOUPE,9.861437,9.861437,4.417519,1,GUADELOUPE
3,101,SAINTE-ROSE,Z,Autres métiers,A2Z70,Techniciens et agents d'encadrement d'exploita...,971,GUADELOUPE,8.636562,8.636562,0.000000,1,GUADELOUPE
4,101,SAINTE-ROSE,O,Ouvriers de la construction et du bâtiment,B0Z21,Ouvriers non qualifiés du gros œuvre du bâtiment,971,GUADELOUPE,14.846788,7.423394,0.000000,1,GUADELOUPE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38727,9411,CORTE GHISONACCIA ALERIA,S,Fonctions sociales et médico-sociales,V3Z80,Autres professionnels para-médicaux (masseurs-...,2B,HAUTE-CORSE,11.159051,9.159051,2.000000,94,CORSE
38728,9411,CORTE GHISONACCIA ALERIA,S,Fonctions sociales et médico-sociales,V4Z83,Educateurs spécialisés,2B,HAUTE-CORSE,2.194130,2.194130,0.000000,94,CORSE
38729,9411,CORTE GHISONACCIA ALERIA,S,Fonctions sociales et médico-sociales,V5Z81,Professionnels de l'animation socioculturelle ...,2B,HAUTE-CORSE,9.379819,0.000000,9.379819,94,CORSE
38730,9411,CORTE GHISONACCIA ALERIA,S,Fonctions sociales et médico-sociales,V5Z82,Sportifs et animateurs sportifs,2B,HAUTE-CORSE,22.540125,0.000000,22.540125,94,CORSE
38731,9411,CORTE GHISONACCIA ALERIA,S,Fonctions sociales et médico-sociales,W1Z80,Formateurs (y compris moniteurs d'auto-école),2B,HAUTE-CORSE,4.323407,0.000000,0.000000,94,CORSE

In [3]:
df15 = df15.iloc[:,[3 ,5 ,6 ,7 , 8, 11, 12]]
df15['Année']=2015
df15 = df15[['Année', 'Libellé Famille métier', 'Libellé du métier' ,'Nom Departement', 'Code département', 'Nom Region', 'Code region',   'Projets de recrutement totaux']]

In [4]:
df16 = pd.read_excel("data/ResMetBE16.xlsx", sheet_name=0)
df16 = df16.iloc[:,[0 ,4 ,6 ,7 , 8, 9, 12, 13]]
df16.columns = ['Année', 'Libellé Famille métier', 'Libellé du métier', 'Code département', 'Nom Departement', 'Projets de recrutement totaux', 'Code region', 'Nom Region']
df16 = df16[['Année', 'Libellé Famille métier', 'Libellé du métier' ,'Nom Departement', 'Code département', 'Nom Region', 'Code region',   'Projets de recrutement totaux']]

In [5]:
df17 = pd.read_excel("data/ResMetBE17.xlsx", sheet_name=1)
df17 = df17.iloc[:,[0 ,4 ,6 ,7 , 8, 9, 12, 13]]
df17.columns = ['Année', 'Libellé Famille métier', 'Libellé du métier', 'Code département', 'Nom Departement', 'Projets de recrutement totaux', 'Code region', 'Nom Region']
df17 = df17[['Année', 'Libellé Famille métier', 'Libellé du métier' ,'Nom Departement', 'Code département', 'Nom Region', 'Code region',   'Projets de recrutement totaux']]

In [6]:
df18 = pd.read_excel("data/ResMetBE18.xlsx", sheet_name=1)
df18 = df18.iloc[:,[0 ,4 ,6 ,7 , 8, 9, 12, 13]]
df18.columns = ['Année', 'Libellé Famille métier', 'Libellé du métier', 'Code département', 'Nom Departement', 'Projets de recrutement totaux', 'Code region', 'Nom Region']
df18 = df18[['Année', 'Libellé Famille métier', 'Libellé du métier' ,'Nom Departement', 'Code département', 'Nom Region', 'Code region',   'Projets de recrutement totaux']]

In [7]:
df19 = pd.read_excel("data/ResMetBE19.xlsx", sheet_name=1)
df19 = df19.iloc[:,[0 ,4 ,6 ,7 , 8, 9, 12, 13]]
df19.columns = ['Année', 'Libellé Famille métier', 'Libellé du métier', 'Code département', 'Nom Departement', 'Projets de recrutement totaux', 'Code region', 'Nom Region']
df19 = df19[['Année', 'Libellé Famille métier', 'Libellé du métier' ,'Nom Departement', 'Code département', 'Nom Region', 'Code region',   'Projets de recrutement totaux']]

In [8]:
df20 = pd.read_excel("data/ResMetBE20.xlsx", sheet_name=1)
df20 = df20.iloc[:,[0 ,4 ,6 ,7 , 8, 9, 12, 13]]
df20.columns = ['Année', 'Libellé Famille métier', 'Libellé du métier', 'Code département', 'Nom Departement', 'Projets de recrutement totaux', 'Code region', 'Nom Region']
df20 = df20[['Année', 'Libellé Famille métier', 'Libellé du métier' ,'Nom Departement', 'Code département', 'Nom Region', 'Code region',   'Projets de recrutement totaux']]

In [12]:
df21 = pd.read_excel("data/Base_open_data_21_def.xlsx", sheet_name=1)

In [13]:
df21

,annee,Code métier BMO,Nom métier BMO,Famille_met,Lbl_fam_met,BE21,NOMBE21,Dept,NomDept,REG,NOM_REG,met,xmet,smet
0,2021,A0Z40,Agriculteurs salariés,Z,Autres métiers,101.0,BASSIN BASSE-TERRE,971,Guadeloupe,1,Guadeloupe,252,189,159
1,2021,A0Z40,Agriculteurs salariés,Z,Autres métiers,102.0,BASSIN GRANDE-TERRE,971,Guadeloupe,1,Guadeloupe,198,144,153
2,2021,A0Z40,Agriculteurs salariés,Z,Autres métiers,105.0,BASSIN CENTRE,971,Guadeloupe,1,Guadeloupe,95,88,79
3,2021,A0Z40,Agriculteurs salariés,Z,Autres métiers,201.0,MARTINIQUE CENTRE,972,Martinique,2,Martinique,143,92,76
4,2021,A0Z40,Agriculteurs salariés,Z,Autres métiers,202.0,MARTINIQUE NORD ATLANTIQUE,972,Martinique,2,Martinique,109,56,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46590,2021,W1Z80,Formateurs,S,Fonctions sociales et médico-sociales,9332.0,HAUT VAR,83,Var,93,Provence-Alpes-Côte d'Azur,37,29,*
46591,2021,W1Z80,Formateurs,S,Fonctions sociales et médico-sociales,9333.0,AIX GARDANNE SALON,13,Bouches-du-Rhône,93,Provence-Alpes-Côte d'Azur,189,99,13
46592,2021,W1Z80,Formateurs,S,Fonctions sociales et médico-sociales,NaN,NaN,06,Alpes-Maritimes,93,Provence-Alpes-Côte d'Azur,10,10,*
46593,2021,W1Z80,Formateurs,S,Fonctions sociales et médico-sociales,NaN,NaN,2A,Corse-du-Sud,94,Corse,12,12,*
46594,2021,W1Z80,Formateurs,S,Fonctions sociales et médico-sociales,NaN,NaN,2B,Haute-Corse,94,Corse,20,*,8

In [9]:
df21 = df21.iloc[:,[0 ,2 ,4 ,7 , 8, 9, 10, 11]]
df21.columns = ['Année', 'Libellé du métier', 'Libellé Famille métier', 'Code département', 'Nom Departement', 'Code region', 'Nom Region', 'Projets de recrutement totaux']
df21 = df21[['Année', 'Libellé Famille métier', 'Libellé du métier' ,'Nom Departement', 'Code département', 'Nom Region', 'Code region',   'Projets de recrutement totaux']]

In [10]:
df = pd.concat([df15, df16, df17, df18, df19, df20, df21])
df

,Année,Libellé Famille métier,Libellé du métier,Nom Departement,Code département,Nom Region,Code region,Projets de recrutement totaux
0,2015,Autres métiers,"Agriculteurs salariés, ouvriers agricoles",GUADELOUPE,971,GUADELOUPE,1.0,45.909687
1,2015,Autres métiers,Conducteurs d'engins agricoles ou forestiers,GUADELOUPE,971,GUADELOUPE,1.0,8.636562
2,2015,Autres métiers,"Jardiniers salariés, paysagistes",GUADELOUPE,971,GUADELOUPE,1.0,9.861437
3,2015,Autres métiers,Techniciens et agents d'encadrement d'exploita...,GUADELOUPE,971,GUADELOUPE,1.0,8.636562
4,2015,Ouvriers de la construction et du bâtiment,Ouvriers non qualifiés du gros œuvre du bâtiment,GUADELOUPE,971,GUADELOUPE,1.0,14.846788
...,...,...,...,...,...,...,...,...
46590,2021,Fonctions sociales et médico-sociales,Formateurs,Var,83,Provence-Alpes-Côte d'Azur,93.0,37
46591,2021,Fonctions sociales et médico-sociales,Formateurs,Bouches-du-Rhône,13,Provence-Alpes-Côte d'Azur,93.0,189
46592,2021,Fonctions sociales et médico-sociales,Formateurs,Alpes-Maritimes,06,Provence-Alpes-Côte d'Azur,93.0,10
46593,2021,Fonctions sociales et médico-sociales,Formateurs,Corse-du-Sud,2A,Corse,94.0,12
46594,2021,Fonctions sociales et médico-sociales,Formateurs,Haute-Corse,2B,Corse,94.0,20

In [11]:
df.to_csv("besoin-main-d'oeuvre-2015-2021.csv")